# Generated by Django 3.1.7 on 2021-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
