# Generated by Django 3.2.4 on 2021-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospede', '0003_alter_hospede_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
