# Generated by Django 3.2.4 on 2021-06-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('data_nascimento', models.DateField()),
                ('tipo_funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.tipo_funcionario')),
            ],
        ),
    ]
