# Generated by Django 3.2.4 on 2021-06-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_rename_tipo_funcionario_id_funcionario_tipo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
